apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: anandvardhandaspipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anandvardhandaspipelinesjavascriptdocker 
    spec:
      containers:
        - name: anandvardhandaspipelinesjavascriptdocker 
          image: akscrtest.azurecr.io/anandvardhandaspipelinesjavascriptdocker 
          ports:
          - containerPort: 8080